name: Test Jekyll Website

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - run: gem install bundler

    - name: install dependencies
      run: make install
    
    - name: serve
      run: make serve &
    
    - name: test
      run: make test
    
    - name: close serve
      run: kill %1
